# Generated by Django 4.2.2 on 2023-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('Email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='netflixUsers',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=220)),
                ('lname', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=220)),
                ('dob', models.DateField()),
            ],
        ),
    ]
