# Generated by Django 4.2.2 on 2023-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('movie_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('yearRelease', models.DateField()),
                ('rating', models.IntegerField()),
                ('path', models.CharField(max_length=250)),
                ('filmType', models.CharField(max_length=250)),
            ],
        ),
    ]
